In [ ]:
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)

2.0.2
2.2.3

In [ ]:
marks = np.array([78,85,92,67,88])
print("marks:", marks)
print("type:",type(marks))

marks: [78 85 92 67 88]
type: <class 'numpy.ndarray'>

Array Operations

In [ ]:
print("Number of dimensions:",marks.ndim)
print("shape:", marks.shape)
print("Number of elements:", marks.size)

Number of dimensions: 1
shape: (5,)
Number of elements: 5

Numpy Operations

In [ ]:
marks = np.array([78,85,92,67,88])

print("original:", marks)
print("Add 5:", marks +5)
print("multiply by 2:", marks * 2)
print("divide by 2:", marks/2)
print("square:", marks **2)

original: [78 85 92 67 88]
Add 5: [83 90 97 72 93]
multiply by 2: [156 170 184 134 176]
divide by 2: [39.  42.5 46.  33.5 44. ]
square: [6084 7225 8464 4489 7744]

In [ ]:
print("Sum:",marks.sum())
print("Mean:",marks.mean())
print("maximum:",marks.max())
print("minimum:",marks.min())

Sum: 410
Mean: 82.0
maximum: 92
minimum: 67

numpy indexing

In [ ]:
print("First mark:", marks[0])
print("Second mark:", marks[1])
print("last mark:", marks[-1])

First mark: 78
Second mark: 85
last mark: 88

numpy slicing

In [ ]:
print("index 1 to 3:", marks[1:4])
print("first three:", marks[:3])
print("from index 2:", marks[2:])
print("every second element:", marks[::2])

index 1 to 3: [85 92 67]
first three: [78 85 92]
from index 2: [92 67 88]
every second element: [78 92 88]

two-dimensional numpy array

In [ ]:
student_marks = np.array([
    [78,85,92],
    [67,88,76],
    [90,95,89]
])

print(student_marks)
print("shape:", student_marks.shape)

[[78 85 92]
 [67 88 76]
 [90 95 89]]
shape: (3, 3)

In [ ]:
print("mean of all values:", student_marks.mean())
print("column wise mean:", student_marks.mean(axis=0))
print("row wise mean:", student_marks.mean(axis=1))

mean of all values: 84.44444444444444
column wise mean: [78.33333333 89.33333333 85.66666667]
row wise mean: [85.         77.         91.33333333]

pandas dataframe

a dataframe is a 2d tabular data structure in pandas

In [ ]:
data = {
    "Name": ["anu","rahul","kiran","priya"],
    "branch": ["cse","aiml","cse","aiml"],
    "marks": [85,91,76,88]
}

df = pd.DataFrame(data)
df

    Name branch  marks
0    anu    cse     85
1  rahul   aiml     91
2  kiran    cse     76
3  priya   aiml     88

inspecting a dataframe

In [ ]:
print("shape:", df.shape)
print("\ncolumns:")
print(df.columns)

shape: (4, 3)

columns:
Index(['Name', 'branch', 'marks'], dtype='object')

In [ ]:
df.head()

    Name branch  marks
0    anu    cse     85
1  rahul   aiml     91
2  kiran    cse     76
3  priya   aiml     88

In [ ]:
df.tail()

    Name branch  marks
0    anu    cse     85
1  rahul   aiml     91
2  kiran    cse     76
3  priya   aiml     88

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   branch  4 non-null      object
 2   marks   4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [ ]:
df.describe()

           marks
count   4.000000
mean   85.000000
std     6.480741
min    76.000000
25%    82.750000
50%    86.500000
75%    88.750000
max    91.000000

selecting columns

In [ ]:
print("marks column:")
print(df["marks"])
print("\nbranch and marks:")
print(df[["branch","marks"]])

marks column:
0    85
1    91
2    76
3    88
Name: marks, dtype: int64

branch and marks:
  branch  marks
0    cse     85
1   aiml     91
2    cse     76
3   aiml     88

In [ ]:
print("first row:")
print(df.iloc[0])

print("\nsecond row")
print(df.iloc[1])

print("\nthird row")
print(df.iloc[0:3])

first row:
Name      anu
branch    cse
marks      85
Name: 0, dtype: object

second row
Name      rahul
branch     aiml
marks        91
Name: 1, dtype: object

third row
    Name branch  marks
0    anu    cse     85
1  rahul   aiml     91
2  kiran    cse     76

In [ ]:
print("first 2 rows and first  2columns:")
print(df.iloc[0:2,0:2])

first 2 rows and first  2columns:
    Name branch
0    anu    cse
1  rahul   aiml

In [ ]:
high_scorers = df[df["marks"]>90]
high_scorers

    Name branch  marks
1  rahul   aiml     91

In [ ]:
print("students from cse:")
display(df[df["branch"]=="cse"])

print("\nstudents scoring 85 or above:")
display(df[df["marks"]>= 85])

students from cse:

    Name branch  marks
0    anu    cse     85
2  kiran    cse     76

students scoring 85 or above:

    Name branch  marks
0    anu    cse     85
1  rahul   aiml     91
3  priya   aiml     88

In [ ]:
data = {
    "name": ["asha","bharat","chetan","divya","esha"],
    "department":["cse","ise","cse","aiml","ise"],
    "marks": [72,91,84,95,68],
    "attendence": [82,94,88,96,75]
}

students = pd.DataFrame(data)
students

     name department  marks  attendence
0    asha        cse     72          82
1  bharat        ise     91          94
2  chetan        cse     84          88
3   divya       aiml     95          96
4    esha        ise     68          75

In [ ]:
print(students["name"])
print(students["marks"])

0      asha
1    bharat
2    chetan
3     divya
4      esha
Name: name, dtype: object
0    72
1    91
2    84
3    95
4    68
Name: marks, dtype: int64

In [ ]:
print(students[students["marks"]>80])

     name department  marks  attendence
1  bharat        ise     91          94
2  chetan        cse     84          88
3   divya       aiml     95          96

In [ ]:
print(students[(students["attendence"]) > 85])

     name department  marks  attendence
1  bharat        ise     91          94
2  chetan        cse     84          88
3   divya       aiml     95          96

In [ ]:
print(students[0:3])

     name department  marks  attendence
0    asha        cse     72          82
1  bharat        ise     91          94
2  chetan        cse     84          88

In [ ]:
data1 = np.array([
    [72,91,84,95,68],
])

print(data1.sum()/5)

82.0

In [ ]:
print(students["marks"].max)

<bound method Series.max of 0    72
1    91
2    84
3    95
4    68
Name: marks, dtype: int64>

In [ ]:
print(students["department"] == "cse")

0     True
1    False
2     True
3    False
4    False
Name: department, dtype: bool

In [ ]:
print(students[(students["marks"]>=80) & (students["attendence"]>=85)])

     name department  marks  attendence
1  bharat        ise     91          94
2  chetan        cse     84          88
3   divya       aiml     95          96

shubh sharma 4ni25cs191